### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by tuvovan** [vinthony/awesome-deep-hdr#1]
hi, I found this paper about HDR synthesis.

Please add this to your repo or add me so that I can make a pull request.

https://paperswithcode.com/paper/deep-hdr-imaging-via-a-non-local-network

Thanks!

**Comment by vinthony** [comment]
Hi, thanks for your interest in this list.

Since more people are working on HDR recently, I will find some time to re-organized this list to a more former way.

Also, I have invited you as a contributor to this list!

Thanks for your contribution in advance!
