### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by tnt-ooo-tnt** [vinthony/awesome-deep-hdr#8]
Here is a project page for 'Deep Chain HDRI'
-> https://siyeong-lee.github.io/hdr_vds_dataset/

And also 'VDS dataset'
-> https://drive.google.com/drive/folders/1i7iTC6t6e_ZhyCq178V3-nN-IS5-5WOe

VDS dataset is also used in 'DiffHDRsyn'

Thank you

**Comment by vinthony** [comment]
Added
